select * from Estadistica_partida;
select * from partida;
select * from Jugador;
select * from Jugador_MejoraPoder;
select * from partida_nivel;
select * from mejorapoder;
select * from obstaculo;
select * from enemigo;
select * from Nivel;